apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bgg-pvc
  labels:
    name: bgg-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 1Gi