apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  labels:
    name: bggapp-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      name: bggapp-pod
      version: v1
  template:
    metadata:
      name: bggapp-pod
      labels:
        name: bggapp-pod
        version: v1
    spec:
      containers:
      - name: bggapp-container
        image: stackupiss/bgg-backend:v2
        imagePullPolicy: IfNotPresent
        env:
        - name: BGG_DB_USER
          value: root
        - name: BGG_DB_HOST
          value: bggdb-svc
        - name: BGG_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: db_password
        ports:
        - name: app-port
          containerPort: 3000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 5
          timeoutSeconds: 5
          failureThreshold: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  labels:
    name: bggapp-svc
spec:
  type: LoadBalancer
  selector:
    name: bggapp-pod
    version: v1
  ports:
  - name: app-svc-port
    port: 80
    targetPort: app-port