---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
  labels:
    name: mysql-pass
type: Opaque
data:
  ROOT_PASSWORD: Y2hhbmdlaXQ=
---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: wpdb-mysql
spec:
  replicas: 1
  secretName: mysql-pass
  mysqlVersion: "5.7"
  volumeSpec:
    persistentVolumeClaim:
      accessModes: ["ReadWriteOnce"]
      storageClassName: do-block-storage
      resources:
        requests:
          storage: 1Gi
---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlDatabase
metadata:
  name: wpdb
spec:
  database: wpdb
  clusterRef:
    name: wpdb-mysql
    namespace: wpns